import { Connector } from "@/components/connectorRedux/ConnectorRedux"
import "./globals.css";

import { Roboto } from "next/font/google";
import { Metadata } from "next"

export const inter = Roboto({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "one tab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${inter.className}`} lang="en">
      <body><Connector>{children}</Connector></body>
    </html>
  );
}
